assessment/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("endpoint.urls"))
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

endpoint/urls.py
from django.urls import path
from endpoint import views

app_name = "endpoint"

urlpatterns = [
    path("", views._home, name="home"),
    path("register/", views._register, name="register"),
    path("login/", views._login, name="login"),
    path("logout/", views._logout, name="logout")
]

endpoint/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from .managers import CustomUserManager


class User(AbstractBaseUser, PermissionsMixin):
    first_name = models.CharField(max_length=100, blank=True, null=True)
    last_name = models.CharField(max_length=100, blank=True, null=True)
    phone = models.CharField(max_length=15, unique=True)
    email = models.EmailField(unique=True)
    avatar = models.ImageField()
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name', 'phone']

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

endpoint/forms.py
from django import forms
from endpoint.models import User


class UserCreateForm(forms.ModelForm):
    """
    A form that inherits from ModelForm,
    and creates a user, with privileges, from the given
    email and password.
    """
    password1 = forms.CharField(
        widget=forms.PasswordInput()
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput()
    )

    error_messages = {
        "password_mismatch": "The two password fields didn’t match.",
    }

    avatar = forms.ImageField()

    class Meta:
        model = User
        fields = [
            "first_name", "last_name", "phone",
            "email", "avatar"
        ]

        widgets = {
            'first_name': forms.TextInput(),
            'last_name': forms.TextInput(),
            'phone': forms.TextInput(),
            'email': forms.EmailInput(),
        }

    def clean_password2(self):
        """
        Check that the two password entries match
        """
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        """
        Save the provided password in hashed format
        """
        user = super(UserCreateForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserLoginForm(forms.Form):
    """
    A form that inherits from the base *Form* class,
    and logs a user, with privileges, from the given 
    email and password.
    """

    email = forms.CharField(
        widget=forms.EmailInput()
    )
    password = forms.CharField(
        widget=forms.PasswordInput()
    )

    error_messages = {
        'invalid_login':
            f"Please enter a correct {email} and password. Note that both "
            "fields may be case-sensitive.",
        'inactive': "This account is inactive.",
    }

endpoint/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth import login, authenticate, logout
from endpoint.forms import UserCreateForm, UserLoginForm
from django.views.decorators.csrf import csrf_exempt
from endpoint.models import User


def _home(request):
    return render(request, "endpoint/home.html")


@csrf_exempt
def _register(request):
    form = UserCreateForm()

    if request.method == "POST":
        form = UserCreateForm(request.POST)

        if form.is_valid():
            first_name = form.cleaned_data.get("first_name")
            last_name = form.cleaned_data.get("last_name")
            email = form.cleaned_data.get("email")
            phone = form.cleaned_data.get("phone")
            avatar = form.cleaned_data.get("avatar")
            password1 = form.cleaned_data.get("password1")
            password2 = form.cleaned_data.get("password2")

            user = User(
                first_name=first_name, last_name=last_name, email=email,
                phone=phone, avatar=avatar, password1=password1, password2=password2
            )
            user.save()

            return HttpResponse("You have successfully registered a user!")

        return HttpResponse(f"{form.error_messages}")

    # return render(request, "endpoint/register.html", {"form": form})
    return HttpResponse("Register Now...")


@csrf_exempt
def _login(request):
    form = UserLoginForm()

    if request.method == "POST":
        form = UserLoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get("email")
            password = form.cleaned_data.get("password")
            user = authenticate(
                request, email=email, password=password
            )
            if user is not None:
                login(request, user)
                return HttpResponse(f"{email}: you have successfully logged in!")
        return HttpResponse(f"{form.error_messages}")

    return HttpResponse("Login Now...")


@csrf_exempt
def _logout(request):
    logout(request)
    return HttpResponse("You have successfully logged out!")

endpoint/templates/endpoint/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Assessment Project</title>
</head>

<body>
    <style>
        * {
            margin: 0;
            padding: 0%;
            box-sizing: content-box;
        }

        section.assessment {
            background-color: azure;
            color: black;
            padding: 30px;
            text-align: center;
            height: 90vh;
        }

        p.h4 {
            font-size: 36px;
        }

        div.auth_endpoints {
            margin-top: 100px;
        }
    </style>

    <section class="assessment">
        <div class="container">
            <p class="h4">
                Home Endpoint
            </p>

            <div class="auth_endpoints">
                <p class="h5">
                    Register endpoint:
                    <a href="{% url "endpoint:register" %}" class="btn btn-success">
                        {% url "endpoint:register" %}
                    </a>
                </p>
                <p class="h5">
                    Login endpoint:
                    <a href="{% url "endpoint:login" %}" class="btn btn-primary">
                        {% url "endpoint:login" %}
                    </a>
                </p>
                <p class="h5">
                    Logout endpoint:
                    <a href="{% url "endpoint:logout" %}" class="btn btn-danger">
                        {% url "endpoint:logout" %}
                    </a>
                </p>
            </div>
        </div>
    </section>

</body>

</html>

endpoint/templates/endpoint/register.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Assessment Project</title>
</head>

<body>
    <style>
        * {
            margin: 0;
            padding: 0%;
            box-sizing: content-box;
        }

        section.assessment {
            background-color: azure;
            color: black;
            padding: 30px;
            text-align: center;
            height: 90vh;
        }

        p.h4 {
            font-size: 36px;
        }

        div.auth_endpoints {
            margin-top: 100px;
        }
    </style>

    <section class="assessment">
        <div class="container">
            <p class="h4">
                Register
            </p>

            <form method="POST" enctype="multipart/form-data">
                {{ form.as_p }}
                <button type="submit" class="btn btn-success">Register</button>
            </form>

        </div>
    </section>

</body>

</html>